In [1]:
import numpy as np
import matplotlib.pyplot as plt
import matplotlib
import pandas as pd


%matplotlib inline

In [5]:
df = pd.read_csv('/content/citrus.csv')

In [6]:
df

            name  diameter  weight  red  green  blue
0         orange      2.96   86.76  172     85     2
1         orange      3.91   88.05  166     78     3
2         orange      4.42   95.17  156     81     2
3         orange      4.47   95.60  163     81     4
4         orange      4.48   95.76  161     72     9
...          ...       ...     ...  ...    ...   ...
9995  grapefruit     15.35  253.89  149     77    20
9996  grapefruit     15.41  254.67  148     68     7
9997  grapefruit     15.59  256.50  168     82    20
9998  grapefruit     15.92  260.14  142     72    11
9999  grapefruit     16.45  261.51  152     74     2

[10000 rows x 6 columns]

In [7]:
df.name[df.name == 'orange'] = 0
df.name[df.name == 'grapefruit'] = 1

df

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

     name  diameter  weight  red  green  blue
0       0      2.96   86.76  172     85     2
1       0      3.91   88.05  166     78     3
2       0      4.42   95.17  156     81     2
3       0      4.47   95.60  163     81     4
4       0      4.48   95.76  161     72     9
...   ...       ...     ...  ...    ...   ...
9995    1     15.35  253.89  149     77    20
9996    1     15.41  254.67  148     68     7
9997    1     15.59  256.50  168     82    20
9998    1     15.92  260.14  142     72    11
9999    1     16.45  261.51  152     74     2

[10000 rows x 6 columns]

In [8]:
X = df.drop('name', axis=1)
Y = df.name

In [9]:
from sklearn.model_selection import train_test_split

In [10]:
from sklearn import preprocessing
min_max_scaler = preprocessing.MinMaxScaler()
X_scale = min_max_scaler.fit_transform(X)
X_scale

array([[0.        , 0.        , 0.74025974, 0.63529412, 0.        ],
       [0.07042254, 0.00738197, 0.66233766, 0.55294118, 0.01851852],
       [0.10822832, 0.04812589, 0.53246753, 0.58823529, 0.        ],
       ...,
       [0.93624907, 0.97133047, 0.68831169, 0.6       , 0.33333333],
       [0.96071164, 0.99216023, 0.35064935, 0.48235294, 0.16666667],
       [1.        , 1.        , 0.48051948, 0.50588235, 0.        ]])

In [11]:
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2, random_state=42)

In [12]:
Y_train = Y_train.astype(np.float32)
Y_test = Y_test.astype(np.float32)

In [13]:
from keras.models import Sequential
from keras.layers import Dense

In [14]:
model = Sequential([    
                    Dense(32, activation='relu', input_shape=(5,)),    
                    Dense(32, activation='relu'),    
                    Dense(1, activation='sigmoid'),])

In [16]:
model.compile(optimizer='sgd',
              loss='binary_crossentropy',
              metrics=['accuracy'])

In [17]:
model.fit(X_train, Y_train, epochs=100)

Epoch 1/100
250/250 [==============================] - 4s 3ms/step - loss: 1.6828 - accuracy: 0.8544
Epoch 2/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3649 - accuracy: 0.8972
Epoch 3/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3062 - accuracy: 0.9069
Epoch 4/100
250/250 [==============================] - 1s 3ms/step - loss: 0.2706 - accuracy: 0.9133
Epoch 5/100
250/250 [==============================] - 1s 3ms/step - loss: 0.2634 - accuracy: 0.9093
Epoch 6/100
250/250 [==============================] - 1s 3ms/step - loss: 0.2429 - accuracy: 0.9139
Epoch 7/100
250/250 [==============================] - 1s 3ms/step - loss: 0.2373 - accuracy: 0.9141
Epoch 8/100
250/250 [==============================] - 1s 3ms/step - loss: 0.2287 - accuracy: 0.9156
Epoch 9/100
250/250 [==============================] - 1s 3ms/step - loss: 0.2266 - accuracy: 0.9147
Epoch 10/100
250/250 [==============================] - 1s 3ms/step - loss: 0.2229 - accuracy: 0.9153
Epoch 11/100
250/250 [==============================] - 1s 3ms/step - loss: 0.2156 - accuracy: 0.9208
Epoch 12/100
250/250 [==============================] - 1s 3ms/step - loss: 0.2208 - accuracy: 0.9145
Epoch 13/100
250/250 [==============================] - 1s 3ms/step - loss: 0.2157 - accuracy: 0.9178
Epoch 14/100
250/250 [==============================] - 1s 3ms/step - loss: 0.2144 - accuracy: 0.9171
Epoch 15/100
250/250 [==============================] - 1s 3ms/step - loss: 0.2151 - accuracy: 0.9174
Epoch 16/100
250/250 [==============================] - 1s 3ms/step - loss: 0.2133 - accuracy: 0.9169
Epoch 17/100
250/250 [==============================] - 1s 3ms/step - loss: 0.2084 - accuracy: 0.9189
Epoch 18/100
250/250 [==============================] - 1s 3ms/step - loss: 0.2150 - accuracy: 0.9186
Epoch 19/100
250/250 [==============================] - 1s 3ms/step - loss: 0.2150 - accuracy: 0.9208
Epoch 20/100
250/250 [==============================] - 1s 3ms/step - loss: 0.2090 - accuracy: 0.9196
Epoch 21/100
250/250 [==============================] - 1s 3ms/step - loss: 0.2107 - accuracy: 0.9169
Epoch 22/100
250/250 [==============================] - 1s 3ms/step - loss: 0.2101 - accuracy: 0.9181
Epoch 23/100
250/250 [==============================] - 1s 3ms/step - loss: 0.2126 - accuracy: 0.9184
Epoch 24/100
250/250 [==============================] - 1s 3ms/step - loss: 0.2136 - accuracy: 0.9149
Epoch 25/100
250/250 [==============================] - 1s 3ms/step - loss: 0.2070 - accuracy: 0.9200
Epoch 26/100
250/250 [==============================] - 1s 3ms/step - loss: 0.2110 - accuracy: 0.9179
Epoch 27/100
250/250 [==============================] - 1s 3ms/step - loss: 0.2043 - accuracy: 0.9202
Epoch 28/100
250/250 [==============================] - 1s 3ms/step - loss: 0.2050 - accuracy: 0.9214
Epoch 29/100
250/250 [==============================] - 1s 3ms/step - loss: 0.2114 - accuracy: 0.9190
Epoch 30/100
250/250 [==============================] - 1s 3ms/step - loss: 0.2065 - accuracy: 0.9171
Epoch 31/100
250/250 [==============================] - 1s 3ms/step - loss: 0.2081 - accuracy: 0.9211
Epoch 32/100
250/250 [==============================] - 1s 3ms/step - loss: 0.2082 - accuracy: 0.9201
Epoch 33/100
250/250 [==============================] - 1s 3ms/step - loss: 0.2062 - accuracy: 0.9181
Epoch 34/100
250/250 [==============================] - 1s 3ms/step - loss: 0.2049 - accuracy: 0.9215
Epoch 35/100
250/250 [==============================] - 1s 3ms/step - loss: 0.2045 - accuracy: 0.9210
Epoch 36/100
250/250 [==============================] - 1s 3ms/step - loss: 0.2063 - accuracy: 0.9185
Epoch 37/100
250/250 [==============================] - 1s 3ms/step - loss: 0.2065 - accuracy: 0.9186
Epoch 38/100
250/250 [==============================] - 1s 3ms/step - loss: 0.2028 - accuracy: 0.9206
Epoch 39/100
250/250 [==============================] - 1s 3ms/step - loss: 0.2038 - accuracy: 0.9206
Epoch 40/100
250/250 [==============================] - 1s 3ms/step - loss: 0.2028 - accuracy: 0.9220
Epoch 41/100
250/250 [==============================] - 1s 3ms/step - loss: 0.2035 - accuracy: 0.9202
Epoch 42/100
250/250 [==============================] - 1s 3ms/step - loss: 0.2040 - accuracy: 0.9210
Epoch 43/100
250/250 [==============================] - 1s 3ms/step - loss: 0.2025 - accuracy: 0.9210
Epoch 44/100
250/250 [==============================] - 1s 3ms/step - loss: 0.2049 - accuracy: 0.9208
Epoch 45/100
250/250 [==============================] - 1s 3ms/step - loss: 0.2009 - accuracy: 0.9205
Epoch 46/100
250/250 [==============================] - 1s 3ms/step - loss: 0.2018 - accuracy: 0.9214
Epoch 47/100
250/250 [==============================] - 1s 3ms/step - loss: 0.2048 - accuracy: 0.9211
Epoch 48/100
250/250 [==============================] - 1s 3ms/step - loss: 0.2009 - accuracy: 0.9212
Epoch 49/100
250/250 [==============================] - 1s 3ms/step - loss: 0.2002 - accuracy: 0.9225
Epoch 50/100
250/250 [==============================] - 1s 3ms/step - loss: 0.2007 - accuracy: 0.9196
Epoch 51/100
250/250 [==============================] - 1s 3ms/step - loss: 0.1989 - accuracy: 0.9220
Epoch 52/100
250/250 [==============================] - 1s 3ms/step - loss: 0.2009 - accuracy: 0.9218
Epoch 53/100
250/250 [==============================] - 1s 3ms/step - loss: 0.2012 - accuracy: 0.9202
Epoch 54/100
250/250 [==============================] - 1s 3ms/step - loss: 0.2000 - accuracy: 0.9212
Epoch 55/100
250/250 [==============================] - 1s 3ms/step - loss: 0.1998 - accuracy: 0.9219
Epoch 56/100
250/250 [==============================] - 1s 3ms/step - loss: 0.1997 - accuracy: 0.9216
Epoch 57/100
250/250 [==============================] - 1s 3ms/step - loss: 0.1988 - accuracy: 0.9214
Epoch 58/100
250/250 [==============================] - 1s 3ms/step - loss: 0.2002 - accuracy: 0.9206
Epoch 59/100
250/250 [==============================] - 1s 3ms/step - loss: 0.2023 - accuracy: 0.9171
Epoch 60/100
250/250 [==============================] - 1s 3ms/step - loss: 0.2010 - accuracy: 0.9212
Epoch 61/100
250/250 [==============================] - 1s 3ms/step - loss: 0.1996 - accuracy: 0.9239
Epoch 62/100
250/250 [==============================] - 1s 3ms/step - loss: 0.2017 - accuracy: 0.9226
Epoch 63/100
250/250 [==============================] - 1s 3ms/step - loss: 0.1991 - accuracy: 0.9196
Epoch 64/100
250/250 [==============================] - 1s 3ms/step - loss: 0.2014 - accuracy: 0.9219
Epoch 65/100
250/250 [==============================] - 1s 3ms/step - loss: 0.2022 - accuracy: 0.9202
Epoch 66/100
250/250 [==============================] - 1s 3ms/step - loss: 0.2007 - accuracy: 0.9186
Epoch 67/100
250/250 [==============================] - 1s 3ms/step - loss: 0.2008 - accuracy: 0.9216
Epoch 68/100
250/250 [==============================] - 1s 3ms/step - loss: 0.2009 - accuracy: 0.9184
Epoch 69/100
250/250 [==============================] - 1s 3ms/step - loss: 0.1998 - accuracy: 0.9231
Epoch 70/100
250/250 [==============================] - 1s 3ms/step - loss: 0.2012 - accuracy: 0.9208
Epoch 71/100
250/250 [==============================] - 1s 3ms/step - loss: 0.2005 - accuracy: 0.9220
Epoch 72/100
250/250 [==============================] - 1s 3ms/step - loss: 0.1995 - accuracy: 0.9196
Epoch 73/100
250/250 [==============================] - 1s 3ms/step - loss: 0.1982 - accuracy: 0.9216
Epoch 74/100
250/250 [==============================] - 1s 3ms/step - loss: 0.1983 - accuracy: 0.9215
Epoch 75/100
250/250 [==============================] - 1s 3ms/step - loss: 0.1982 - accuracy: 0.9235
Epoch 76/100
250/250 [==============================] - 1s 3ms/step - loss: 0.1980 - accuracy: 0.9220
Epoch 77/100
250/250 [==============================] - 1s 3ms/step - loss: 0.1994 - accuracy: 0.9222
Epoch 78/100
250/250 [==============================] - 1s 3ms/step - loss: 0.1986 - accuracy: 0.9236
Epoch 79/100
250/250 [==============================] - 1s 3ms/step - loss: 0.2013 - accuracy: 0.9222
Epoch 80/100
250/250 [==============================] - 1s 3ms/step - loss: 0.1998 - accuracy: 0.9190
Epoch 81/100
250/250 [==============================] - 1s 3ms/step - loss: 0.1990 - accuracy: 0.9227
Epoch 82/100
250/250 [==============================] - 1s 3ms/step - loss: 0.1985 - accuracy: 0.9229
Epoch 83/100
250/250 [==============================] - 1s 3ms/step - loss: 0.1997 - accuracy: 0.9230
Epoch 84/100
250/250 [==============================] - 1s 3ms/step - loss: 0.2024 - accuracy: 0.9199
Epoch 85/100
250/250 [==============================] - 1s 3ms/step - loss: 0.1983 - accuracy: 0.9210
Epoch 86/100
250/250 [==============================] - 1s 3ms/step - loss: 0.1996 - accuracy: 0.9201
Epoch 87/100
250/250 [==============================] - 1s 3ms/step - loss: 0.2007 - accuracy: 0.9199
Epoch 88/100
250/250 [==============================] - 1s 3ms/step - loss: 0.1977 - accuracy: 0.9243
Epoch 89/100
250/250 [==============================] - 1s 3ms/step - loss: 0.1985 - accuracy: 0.9208
Epoch 90/100
250/250 [==============================] - 1s 3ms/step - loss: 0.1971 - accuracy: 0.9214
Epoch 91/100
250/250 [==============================] - 1s 3ms/step - loss: 0.1999 - accuracy: 0.9211
Epoch 92/100
250/250 [==============================] - 1s 3ms/step - loss: 0.1982 - accuracy: 0.9216
Epoch 93/100
250/250 [==============================] - 1s 3ms/step - loss: 0.1991 - accuracy: 0.9200
Epoch 94/100
250/250 [==============================] - 1s 3ms/step - loss: 0.1981 - accuracy: 0.9220
Epoch 95/100
250/250 [==============================] - 1s 3ms/step - loss: 0.1993 - accuracy: 0.9186
Epoch 96/100
250/250 [==============================] - 1s 3ms/step - loss: 0.1968 - accuracy: 0.9212
Epoch 97/100
250/250 [==============================] - 1s 3ms/step - loss: 0.1981 - accuracy: 0.9225
Epoch 98/100
250/250 [==============================] - 1s 3ms/step - loss: 0.1982 - accuracy: 0.9215
Epoch 99/100
250/250 [==============================] - 1s 3ms/step - loss: 0.2015 - accuracy: 0.9214
Epoch 100/100
250/250 [==============================] - 1s 3ms/step - loss: 0.1988 - accuracy: 0.9240

In [18]:
model.evaluate(X_test, Y_test)

63/63 [==============================] - 1s 3ms/step - loss: 0.1992 - accuracy: 0.9280

[0.19920951128005981, 0.9279999732971191]